DROP IF TABLE EXISTS `user`;
CREATE TABLE `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` INTEGER,
  `age` INTEGER DEFAULT NULL,
  `password` varchar(45) DEFAULT NULL,
  `createTimeStamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateTimeStamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;